### ISSUE TITLE
Using as a Flex-box child

### ISSUE THREAD

**Issue by jamiehill** [Swizec/useDimensions#6]
This is super neat/simple, so many thanks for putting it out.

I'm having an issue using it though, to compute the size of my component, being the child of a flex container.  [See example here](https://codesandbox.io/s/zzq37m3j6l)

It doesn't seem to properly recompute as you change the browser size.  
I'm basically wanting the component to fill all available width, and provide the re-calculated dimensions to it's children  - a canvas in the real world scenario.

Thoughts?

**Comment by oskarsikow** [comment]
I had the same problem and the work-around I found was to put the "ref-element" inside a div ("container") inside the "flex-child". Have "Container" flex: 1 and position: relative, then "ref-element" position: absolute and height/width: 100%. 
Seems to fix it!

**Comment by Swizec** [comment]
One thing I noticed with the codesandbox example is that codesandbox doesn't seem to trigger `window.resize` events when you just resize the internal browser. Numbers start changing when you resize the actual Chrome window.

And I've noticed it works in the upward direction. That is, when you resize teh window to be bigger. Doesn't work in the other direction and I think that's because the parent div isn't actually shrinking.

When you have a flexbox div trying to take up 100%, and the insides are bigger than 100%, I don't think it can actually shrink. Can it?

A possible solution might be to add an overflow so the parent div is allowed to shrink, then `useLayoutEffect` might give us a chance to resize the internal div.

Something like this: https://codesandbox.io/s/gifted-montalcini-6n2ul


Sorry for the extremely very late reply 😅
